---
title: "Plotly 3D drug similarity scatterplots"
output:
  html_document: default
  html_notebook: default
---

Initial 3D scatterplots:

```{r}
## this script visualizes the similarities in phenotypic, target and structural space.
suppressMessages(library(plyr))
suppressMessages(library(dplyr))
suppressMessages(library(data.table))
suppressMessages(library(ggplot2))
suppressMessages(library(tidyr))
suppressMessages(library(ggrepel))
suppressMessages(library(gdata))
suppressMessages(library(scatterplot3d))
suppressMessages(library(plotly))
```

```{r}
######################################################################################T
# Set directories and import files -----
######################################################################################T
#Dir_input<-"/Users/nicholasclark/Desktop/Git/Public_Github/hms_drug"
#setwd(Dir_input)

cube_table<-read.csv("sim_table_chem_jaccard_pheno.csv")%>%arrange(cmpd1)
toolscore_table<-read.csv("toolscore_mapped_lincs.csv")

######################################################################################T
# create grouped table -----
######################################################################################T
query_cmpds<-unique(cube_table$cmpd1)
cube_table.g<-dlply(cube_table,.(cmpd1),c)

######################################################################################T
# Example query #1: show all compounds in relation to 10101 -----
######################################################################################T
c.query<-10101

c.data<-as.data.frame(cube_table.g[[match(c.query,query_cmpds)]])

## add additional qc filters
c.data<-as.data.frame(cube_table.g[[match(c.query,query_cmpds)]])%>%
  filter(n_pairs>5)%>%
  filter(n_common>5)

c.data$cmpd2 = factor(c.data$cmpd2)
p <- plot_ly(c.data, x = ~chem_sim, y = ~jaccard_sim, z = ~pearson_corr, color = ~cmpd2) %>%
  add_markers() %>%
  layout(scene = list(xaxis = list(title = 'Chemical Similarity',
                                   range = c(-0.1,1.1)),
                      yaxis = list(title = 'Jaccard Similarity',
                                   range = c(-0.1,1.1)),
                      zaxis = list(title = 'Pearson Correlation',
                                   range = c(-1.1,1.1))))
p

#scatterplot3d(c.data$chem_sim,c.data$jaccard_sim,c.data$pearson_corr)
## would be better to have the limits fixed limits:
# x=c(0,1),y=(0,1),z(-1,1)
```

```{r}
######################################################################################T
# Example query #2: show all ERK inhibitors in relation to best ERK inhibitor -----
######################################################################################T
c.query_gene<-c(5595,5594)
c.selectivity_treshold<-0.3
c.inhibitors<-toolscore_table%>%filter(gene_id %in% c.query_gene & selectivity>=c.selectivity_treshold)%>%
  filter(source_id %in% query_cmpds)%>%
  arrange(desc(tool_score))
c.best_inhibitor<-c.inhibitors$source_id[1]

c.data2<-as.data.frame(cube_table.g[[match(c.best_inhibitor,query_cmpds)]])%>%
  filter(cmpd2 %in% c.inhibitors$source_id)

## add additional qc filters
c.data2<-as.data.frame(cube_table.g[[match(c.best_inhibitor,query_cmpds)]])%>%
  filter(cmpd2 %in% c.inhibitors$source_id)%>%
  filter(n_pairs>5)%>%
  filter(n_common>5)

c.data2$cmpd2 = factor(c.data2$cmpd2)
q <- plot_ly(c.data2, x = ~chem_sim, y = ~jaccard_sim, z = ~pearson_corr, color = ~cmpd2) %>%
  add_markers() %>%
  layout(scene = list(xaxis = list(title = 'Chemical Similarity',
                                   range = c(-0.1,1.1)),
                      yaxis = list(title = 'Jaccard Similarity',
                                   range = c(-0.1,1.1)),
                      zaxis = list(title = 'Pearson Correlation',
                                   range = c(-1.1,1.1))))
q

#scatterplot3d(c.data$chem_sim,c.data$jaccard_sim,c.data$pearson_corr)
## would be better to have the limits fixed limits:
# x=c(0,1),y=(0,1),z(-1,1)
```
