FROM rocker/rstudio-stable:3.4.2

RUN apt-get update -qq && \
    apt-get install -y \
    pkg-config \
    libnlopt-dev \
    libmariadb-client-lgpl-dev \
    zlib1g-dev \
    libssh2-1-dev \
    libxml2-dev \
    curl \
    libpng-dev \
    sudo \
    wget \
    xclip \
    git

RUN export ADD=shiny && bash /etc/cont-init.d/add

RUN R -e "install.packages('readr', repos = 'https://mran.microsoft.com/snapshot/2017-11-28')"
RUN R -e "install.packages('shiny', repos = 'https://mran.microsoft.com/snapshot/2017-11-28')"
RUN R -e "install.packages('shiny.semantic', repos = 'https://mran.microsoft.com/snapshot/2017-11-28')"
RUN R -e "install.packages('shinyjs', repos = 'https://mran.microsoft.com/snapshot/2017-11-28')"
RUN R -e "install.packages('DT', repos = 'https://mran.microsoft.com/snapshot/2017-11-28')"
RUN R -e "install.packages('dplyr', repos = 'https://mran.microsoft.com/snapshot/2017-11-28')"
RUN R -e "install.packages('crosstalk', repos = 'https://mran.microsoft.com/snapshot/2017-11-28')"
RUN R -e "install.packages('plotly', repos = 'https://mran.microsoft.com/snapshot/2017-11-28')"
RUN R -e "install.packages('markdown', repos = 'https://mran.microsoft.com/snapshot/2017-11-28')"
RUN R -e "install.packages('clipr', repos = 'https://mran.microsoft.com/snapshot/2017-11-28')"
RUN R -e "install.packages('rclipboard', repos = 'https://mran.microsoft.com/snapshot/2017-11-28')"
RUN R -e "install.packages('rsconnect', repos = 'https://mran.microsoft.com/snapshot/2017-11-28')"
RUN R -e "install.packages('remotes', repos = 'https://mran.microsoft.com/snapshot/2018-08-09')"

RUN R -e "remotes::install_github('aws.s3')"
